# typed: true

module Orange
  class Address
    class State < T::Enum
      enums do
        AL = new("AL")
        AK = new("AK")
        AZ = new("AZ")
        AR = new("AR")
        CA = new("CA")
        CO = new("CO")
        CT = new("CT")
        DE = new("DE")
        FL = new("FL")
        GA = new("GA")
        HI = new("HI")
        ID = new("ID")
        IL = new("IL")
        IN = new("IN")
        IA = new("IA")
        KS = new("KS")
        KY = new("KY")
        LA = new("LA")
        ME = new("ME")
        MD = new("MD")
        MA = new("MA")
        MI = new("MI")
        MN = new("MN")
        MS = new("MS")
        MO = new("MO")
        MT = new("MT")
        NE = new("NE")
        NV = new("NV")
        NH = new("NH")
        NJ = new("NJ")
        NM = new("NM")
        NY = new("NY")
        NC = new("NC")
        ND = new("ND")
        OH = new("OH")
        OK = new("OK")
        OR = new("OR")
        PA = new("PA")
        RI = new("RI")
        SC = new("SC")
        SD = new("SD")
        TN = new("TN")
        TX = new("TX")
        UT = new("UT")
        VT = new("VT")
        VA = new("VA")
        WA = new("WA")
        WV = new("WV")
        WI = new("WI")
        WY = new("WY")
        DC = new("DC")
        AS = new("AS")
        GU = new("GU")
        MP = new("MP")
        PR = new("PR")
        UM = new("UM")
        VI = new("VI")
      end
    end
  end
end
